/* eslint-disable @typescript-eslint/no-explicit-any */
import { Page, Text, View, Document, Image, StyleSheet } from '@react-pdf/renderer';
import { UserFormData } from '../user/UserPage';

const styles = StyleSheet.create({
    page: {
        padding: 20,
        fontSize: 10,
        backgroundColor: '#f7f7f7',
    },
    header: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
        paddingBottom: 10,
        borderBottom: '2px solid #4A90E2',
    },
    logo: {
        width: 50,
        height: 50,
    },
    title: {
        fontSize: 24,
        color: '#4A90E2',
        fontWeight: 'bold',
    },
    metadata: {
        fontSize: 10,
        color: '#555',
    },
    headerRow: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 8,
        paddingHorizontal: 10,
        borderBottom: '3px solid #000',
        fontSize: 13
    },
    productRow: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 8,
        paddingHorizontal: 10,
        borderBottom: '1px solid #ddd',
    },
    productRowAlt: {
        backgroundColor: '#eaeaea',
    },
    productText: {
        fontSize: 10,
        color: '#333',
    },
});

const user: UserFormData = JSON.parse(localStorage.getItem('user') || '{}');

const PdfDocument = ({ formData }: any) => (
    <Document>
        <Page size="A4" style={styles.page}>
            {/* Header with Logo and Metadata */}
            <View style={styles.header}>
                <Image
                    src={user.image} // Placeholder for logo/image
                    style={styles.logo}
                />
                <View>
                    <Text style={styles.title}>{user.name}</Text>
                    <Text style={styles.metadata}>{user.email}</Text>
                    <Text style={styles.metadata}>{user.phone}</Text>
                    <Text style={styles.metadata}>{user.address}</Text>
                </View>
                <View>
                    <Text style={styles.metadata}>Date: {new Date().toLocaleDateString()}</Text>
                    <Text style={styles.metadata}>Generated by: Krutik</Text>
                </View>
            </View>

            {/* Products List */}
            {formData.type1.length && <View>
                <View
                    style={[
                        styles.headerRow
                    ]}
                >
                    <Text style={styles.productText}>NAME</Text>
                    <Text style={styles.productText}>Length</Text>
                    <Text style={styles.productText}>Breath</Text>
                    <Text style={styles.productText}>Depth</Text>
                    <Text style={styles.productText}>Price</Text>
                </View>
                {formData.type1.map((product: any, index: number) => {
                    console.log(formData)
                    return (
                        <View
                            key={index}
                            style={[
                                styles.productRow,
                                index % 2 === 0 ? styles.productRowAlt : {}, // Alternate row coloring
                            ]}
                        >
                            <Text style={styles.productText}>{product.name}</Text>
                            <Text style={styles.productText}>{product.length}</Text>
                            <Text style={styles.productText}>{product.breadth}</Text>
                            <Text style={styles.productText}>{product.depth}</Text>
                            <Text style={styles.productText}>{product.price}</Text>
                        </View>
                    )
                })}
            </View>}
            {formData.type2.length && <View break>
                <View
                    style={[
                        styles.headerRow
                    ]}
                >
                    <Text style={styles.productText}>NAME</Text>
                    <Text style={styles.productText}>Rate</Text>
                    <Text style={styles.productText}>Quality</Text>
                    <Text style={styles.productText}>Price</Text>
                </View>
                {formData.type2.map((product: any, index: number) => (
                    <View
                        key={index}
                        style={[
                            styles.productRow,
                            index % 2 === 0 ? styles.productRowAlt : {}, // Alternate row coloring
                        ]}
                    >
                        <Text style={styles.productText}>{product.name}</Text>
                        <Text style={styles.productText}>Rate: {product.rate}</Text>
                        <Text style={styles.productText}>Quantity: {product.quantity}</Text>
                        <Text style={styles.productText}>Price: {product.price}</Text>
                    </View>
                ))}
            </View>}
            <View
                style={{
                    display: 'flex',
                    flexDirection: 'row',
                    justifyContent: 'flex-end',
                    marginTop: 10,
                    paddingTop: 10,
                }}
            >
                <Text
                    style={{
                        fontSize: 14,
                        color: '#333',
                        fontWeight: 'bold',
                        borderBottom: '2px solid #4A90E2',

                    }}
                >
                    Total Amount: {formData.totalAmount}
                </Text>    
            </View>
            <View
                style={{
                    display: 'flex',
                    flexDirection: 'row',
                    justifyContent: 'flex-end',
                    marginTop: 10,
                    paddingTop: 10,
                }}
            >
                <Image
                    src={user.signature}
                    style={{
                        width: 150,
                        height: 100,
                    }}
                />
            </View>
        </Page>
    </Document>
);

export default PdfDocument;
